name: bob

dependencies:
  - base

library:
  exposed-modules: Bob
  source-dirs: src
  dependencies:
    - regex-pcre

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - hspec
